PROG_CXX = echod
SRCS     = echod.cc
MK_MAN   = no
NO_OBJ   = noobj

CXXFLAGS  = -g
CXXFLAGS += -std=c++17 -Wall -Wextra -Wno-unused-parameter -I/usr/local/include
LDFLAGS  += -L/usr/local/lib -lev

.include <bsd.prog.mk>
